### PR TITLE
Update README_ZH.md

### PR DESCRIPTION
**Pull request by smartczy**
---
name: Pull request
about: Propose changes to the code
title: 'fix markdown error'
labels: ''
assignees: ''
---

## 1. Are you opening this pull request for bug-fixs, optimizations or new feature?
fix the chinese document's typo error

## 4. Checklist

- [ ] I have squashed all insignificant commits.
- [ ] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [ ] I have written unit tests and verified that all tests passes (if needed).
- [ ] I have documented feature info on the README (only when this PR is adding a new feature).
- [ ] (optional) I am willing to help maintain this change if there are issues with it later.

### CODE REVIEW

**Comment by panjf2000** [comment]
这里改了什么东西？看着一样啊！

**Comment by smartczy** [comment]
Round-Roubin前有个特殊符号，导致渲染出来有乱码。
1039行没改动，不知道为啥有diff

**Comment by panjf2000** [comment]
特殊符号看到了，不过第二个 diff 你还是看下，用 git diff 查一下，解决一下。

**Comment by smartczy** [comment]
尝试了几个编辑器在删除这个特殊字符的时候都会导致第二个diff，很奇怪。我把这个commit reset掉重新提了。

**Pull request closed without merging**
