### PR TITLE
every connection use it's own codec

### PR DESCRIPTION
**Pull request by firedtoad**
---
name: Pull request
about: Propose changes to the code
title: ''
labels: ''
assignees: ''
---

## 4. Checklist

- [ ] I have squashed all insignificant commits.
- [ ] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [ ] I have written unit tests and verified that all tests passes (if needed).
- [ ] I have documented feature info on the README (only when this PR is adding a new feature).
- [ ] (optional) I am willing to help maintain this change if there are issues with it later.

### CODE REVIEW

**Comment by panjf2000** [comment]
This inspires me that the `codec` can be removed from `eventloop` struct, just move the `el.codec.Encode(c, out)` to `c.write([]byte)` function:
https://github.com/panjf2000/gnet/blob/240c9fbdac62ad849eeb24f3d89e425a96bad1f0/connection_unix.go#L109-L128
as `c.codec.(c, buf)`, this way we can keep all `Decode()` and `Encode()` actions in the scope of `conn` and also remove other usages of `el.codec`, in both Unix and Windows platforms.

https://github.com/panjf2000/gnet/blob/240c9fbdac62ad849eeb24f3d89e425a96bad1f0/connection_unix.go#L57
In the end, update the `newTCPConn()`, replace `el.codec` with `el.svr.codec`.

Could you do these changes in this PR?

**Comment by panjf2000** [comment]
@firedtoad

**Comment by panjf2000** [comment]
I just find out there is plenty of code to change, I will just make these changes myself and when I finish it, this PR should be unnecessary, but still, thank you for this idea.

**Comment by firedtoad** [comment]
No I don't think so,What I do really want is every connection has it's own codec 
So I can change the codec after cipher exchange like ecdh

**Pull request closed without merging**
