### PR TITLE
opt: improve the spinlock

### PR DESCRIPTION
**Pull request by firedtoad**
---
name: Pull request
about: Propose changes to the code
title: ''
labels: ''
assignees: ''
---

## 4. Checklist

- [ ] I have squashed all insignificant commits.
- [ ] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [ ] I have written unit tests and verified that all tests passes (if needed).
- [ ] I have documented feature info on the README (only when this PR is adding a new feature).
- [ ] (optional) I am willing to help maintain this change if there are issues with it later.

### CODE REVIEW

**Comment by panjf2000** [comment]
Why bother?
Does this make any difference? What's the benchmark result?

**Comment by firedtoad** [comment]
This is the result running on Intel I5-6500 CPU@3.2GHz
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 262K (x4)
  L3 Unified 6291K (x1)
BenchmarkOriginSpinLock
BenchmarkOriginSpinLock-4       45932941                25.9 ns/op
BenchmarkBackOffSpinLock
BenchmarkBackOffSpinLock-4      70778504                17.0 ns/op
PASS

**Comment by panjf2000** [comment]
> This is the result running on Intel I5-6500 [CPU@3.2GHz](mailto:CPU@3.2GHz)
> CPU Caches:
> L1 Data 32K (x4)
> L1 Instruction 32K (x4)
> L2 Unified 262K (x4)
> L3 Unified 6291K (x1)
> BenchmarkOriginSpinLock
> BenchmarkOriginSpinLock-4 45932941 25.9 ns/op
> BenchmarkBackOffSpinLock
> BenchmarkBackOffSpinLock-4 70778504 17.0 ns/op
> PASS

Thanks but please provide the original benchmark result outputs by running `go test -bench=. -benchmem=true`

**Comment by firedtoad** [comment]
This is the origin benchmark result 
E:\dev\tgnet\test>go test -bench=. -benchmem=true
goos: windows
goarch: amd64
pkg: tgnet/test
BenchmarkOriginSpinLock-4       44683564                27.3 ns/op             0 B/op          0 allocs/op
BenchmarkBackOffSpinLock-4      70778504                16.7 ns/op             0 B/op          0 allocs/op
PASS
ok      tgnet/test      3.353s

**Comment by firedtoad** [comment]
this is the result running on quater core cpu linux server
cat /proc/cpuinfo | grep CPU
model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
go test -bench . spin_test.go -benchmem=true
goos: linux
goarch: amd64
BenchmarkOriginSpinLock-4       27869398                39.7 ns/op             0 B/op          0 allocs/op
BenchmarkBackOffSpinLock-4      45706514                23.8 ns/op             0 B/op          0 allocs/op
PASS
ok      command-line-arguments  4.069s

**Comment by panjf2000** [comment]
Sorry for the delay, I've been so busy for a while that I completely forgot about this PR, merging it now.

**Comment by firedtoad** [comment]
thanks

Andy Pan <notifications@github.com> 于2021年1月23日周六 上午1:21写道：

**Pull request merged**
